### PR TITLE
finalise spiral scouting and move to a waypoint

### PR DESCRIPTION
**Pull request by reinaldomaslim**
next: working on quadrant zigzag scouting and station-keep

### CODE REVIEW

**Review by ron1818 — CHANGES_REQUESTED** [review]
i changed scout and zigzag yesterday. I think I corrected the problems. you can check my latest version (nav-dev branch). If zigzag and scout works, this merge is not required

**Review by ron1818 — COMMENTED** [review]
move_base.launch can include /fake/ directory, I corrected the yaml files.

**Comment by ron1818** [comment]
i will do the difff and make them up to date

**Comment by reinaldomaslim** [comment]
Ok boss, what do you mean with difff?

**Comment by reinaldomaslim** [comment]
for i in range(0,N-1):
waypoints=straight_waypoints(self, corner[i], corner[i+1], waypoints)

yes i have pulled the previous one, but there's error. here must change to
for i in range(0,len(corner)-1):

and in movebase_waypoint:

q_angle = quaternion_from_euler(0, 0, atan2(target.x-self.y0, target.y-self.x0))

must be

q_angle = quaternion_from_euler(0, 0, atan2(target.y-self.y0, target.x-self.x0))

**Pull request merged**
